# Generated by Django 3.0.5 on 2020-04-22 23:26

import app.src.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200421_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='time',
            field=models.CharField(max_length=8, validators=[app.src.validators.reservationTimeValidator]),
        ),
    ]
