# Generated by Django 3.0.5 on 2020-04-24 01:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20200422_1926'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='date',
            field=models.DateTimeField(default=datetime.date(2020, 4, 23)),
        ),
    ]
