# Generated by Django 3.0.5 on 2020-04-24 11:59

import app.src.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20200423_2211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='date',
            field=models.CharField(max_length=9, validators=[app.src.validators.reservationDateValidator]),
        ),
    ]
