# Generated by Django 3.0.5 on 2020-04-24 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20200424_0759'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='requests',
            field=models.CharField(default='None', max_length=256),
        ),
    ]
