# Generated by Django 3.0.5 on 2020-04-26 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20200426_1820'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='age',
        ),
    ]
