# Generated by Django 3.0.5 on 2020-04-26 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_remove_client_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
