# Generated by Django 3.0.5 on 2020-04-28 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_admin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='verified',
            new_name='confirmed',
        ),
        migrations.AddField(
            model_name='reservation',
            name='confirmation_nonce',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
