# Generated by Django 3.0.5 on 2020-04-28 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_auto_20200428_0858'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admin',
            name='email',
        ),
        migrations.AlterField(
            model_name='admin',
            name='password',
            field=models.CharField(default='password', max_length=256),
        ),
        migrations.AlterField(
            model_name='admin',
            name='username',
            field=models.CharField(default='Admin', max_length=24, unique=True),
        ),
    ]
