# Generated by Django 3.0.5 on 2020-04-28 21:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_auto_20200428_1649'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='email',
            field=models.EmailField(default='no-email@provided.com', max_length=254, unique=True, validators=[django.core.validators.EmailValidator()]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='admin',
            name='password',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='admin',
            name='username',
            field=models.CharField(default='admin', max_length=24),
        ),
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.EmailField(max_length=254, null=True, unique=True, validators=[django.core.validators.EmailValidator()]),
        ),
    ]
